name: Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore MarchzinsBonusTool/MarchzinsBonusTool.sln

    - name: Build
      run: dotnet build MarchzinsBonusTool/MarchzinsBonusTool.sln --no-restore --configuration Release

    - name: Run unit tests
      run: dotnet test MarchzinsBonusTool/MarchzinsBonusTool.sln --no-build --configuration Release --logger trx

    - name: Run GUI tests (Linux with Xvfb)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb
        xvfb-run -a dotnet test MarchzinsBonusTool/MarchzinsBonusTool.sln --no-build --configuration Release --filter "Category=GUI"

    - name: Run GUI tests (Windows)
      if: matrix.os == 'windows-latest'
      run: dotnet test MarchzinsBonusTool/MarchzinsBonusTool.sln --no-build --configuration Release --filter "Category=GUI"
